//                     
//                     
//                     Only one graphics engine can be defined!
//                     
//                     ---- DONT DEFINE MORE THAN ONE !!! -----

{.$define USE_VENOMGFX}
{$define USE_GRAPH}
{.$define USE_PTC}
{.$define USE_SVGALIB}

{
   This definition file manages the used graphics routines to implement FPPixlCanvas for DOS or 
   
   Linux console for graphics output without windows or xserver, directly into the console.


}
